export  const ADD_FAV_POST_ITEM ="ADD_ORDER_ITEM";
export  const DELETE_FAV_POST_ITEM ="DELETE_ORDER_ITEM";

export  const UPDATE_TEMP_POST_ITEM ="DELETE_ORDER_ITEM";

export  const SET_USER_LOGIN ="SET_USER_LOGIN";
export  const DELETE_USER_LOGIN ="DELETE_USER_LOGIN";

export  const ALERT_SYSTEM_SHOW ="ALERT_SYSTEM_SHOW";
